2018-06-07 12:23:08,862 ERROR: Exception on /messages [GET] [in c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask_login\utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Woong Wen Tat\flask-microblog\app\main\routes.py", line 180, in messages
    current_user.add_notification('unread_message_count', user.new_messages())
AttributeError: 'function' object has no attribute 'new_messages'
2018-06-07 12:24:48,759 INFO: Microblog startup [in C:\Users\Woong Wen Tat\flask-microblog\app\__init__.py:81]
2018-06-07 12:24:58,040 INFO: Microblog startup [in C:\Users\Woong Wen Tat\flask-microblog\app\__init__.py:81]
2018-06-07 12:25:07,214 INFO: Microblog startup [in C:\Users\Woong Wen Tat\flask-microblog\app\__init__.py:81]
2018-06-07 12:25:11,114 ERROR: Exception on /messages [GET] [in c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask_login\utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Woong Wen Tat\flask-microblog\app\main\routes.py", line 180, in messages
    current_user.add_notification('unread_message_count', user.new_messages())
AttributeError: 'function' object has no attribute 'new_messages'
2018-06-07 12:26:47,321 INFO: Microblog startup [in C:\Users\Woong Wen Tat\flask-microblog\app\__init__.py:81]
2018-06-07 12:27:18,565 ERROR: Exception on /index [POST] [in c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask_login\utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Woong Wen Tat\flask-microblog\app\main\routes.py", line 35, in index
    db.session.commit()
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\sqlalchemy\orm\scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\sqlalchemy\orm\session.py", line 906, in commit
    self.transaction.commit()
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\sqlalchemy\orm\session.py", line 468, in commit
    self.session.dispatch.after_commit(self.session)
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\sqlalchemy\event\attr.py", line 218, in __call__
    fn(*args, **kw)
  File "C:\Users\Woong Wen Tat\flask-microblog\app\models.py", line 136, in after_commit
    add_to_index(obj.__tablename__, obj)
  File "C:\Users\Woong Wen Tat\flask-microblog\app\search.py", line 11, in add_to_index
    index=index, doc_type=index, id=model.id, body=payload)
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\elasticsearch\client\utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\elasticsearch\client\__init__.py", line 319, in index
    _make_path(index, doc_type, id), params=params, body=body)
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\elasticsearch\transport.py", line 314, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\elasticsearch\connection\http_urllib3.py", line 175, in perform_request
    raise ConnectionError('N/A', str(e), e)
ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x04E2E830>: Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x04E2E830>: Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it)
2018-06-07 14:29:49,319 INFO: Microblog startup [in C:\Users\Woong Wen Tat\flask-microblog\app\__init__.py:81]
