2018-06-07 15:10:34,174 ERROR: Exception on /api/users [GET] [in c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\woongw~1\envs\flaskt~1\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Woong Wen Tat\flask-microblog\app\api\users.py", line 13, in get_users
    page = request.args.get('page', 1, type=int)
NameError: global name 'request' is not defined
2018-06-07 15:11:17,505 INFO: Microblog startup [in C:\Users\Woong Wen Tat\flask-microblog\app\__init__.py:84]
2018-06-07 15:21:11,500 INFO: Microblog startup [in C:\Users\Woong Wen Tat\flask-microblog\app\__init__.py:84]
2018-06-07 15:21:19,927 INFO: Microblog startup [in C:\Users\Woong Wen Tat\flask-microblog\app\__init__.py:84]
